{{- if .Values.blackbox_exporter.enabled }}
{{ $values := .Values.blackbox_exporter }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $values.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: {{ $values.name }}
spec:
  replicas: {{ $values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
      app.kubernetes.io/instance: {{ $values.name }}
  template:
    metadata:
      name: {{ $values.name }}
      labels:
        app.kubernetes.io/name: blackbox-exporter
        app.kubernetes.io/instance: {{ $values.name }}
    spec:
      restartPolicy: Always
      automountServiceAccountToken: false
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: blackbox-exporter
      {{- with $values.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: blackbox-exporter
        image: {{ $values.image.repository }}:{{ $values.image.tag }}
        imagePullPolicy: {{ $values.image.pullPolicy }}
        {{- with $values.args }}
        args:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 9115
          name: http
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          httpGet:
            path: /-/healthy
            port: http
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          httpGet:
            path: /-/healthy
            port: http
        {{- with $values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
