{{- if .Values.management.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.management.configSecret" . }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
stringData:
  management.json: |-
    {{- .Values.management.config | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.management.envSecret" . }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.management.env | nindent 2 }}
{{- end }}
