{{- if .Values.serviceAccount.create }}
{{- $name := include "ucloud.serviceAccountName" . }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}-role
  namespace: {{ .Values.apps.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "services", "events"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["*"]
- apiGroups: ["kubevirt.io", "cdi.kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}-role-binding
  namespace: {{ .Values.apps.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}-role
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
