{{- if .Values.relay.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.relay.envSecret" . }}
  labels:
    {{- include "netbird.relay.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.relay.env | nindent 2 }}
{{- end }}
