kind: Service
apiVersion: v1
metadata:
  name: {{ include "ucloud.provider.deploymentName" . }}
  {{- with .Values.provider.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.provider.service.type }}
  ports:
  - name: metrics
    port: 7867
    targetPort: metrics
    protocol: TCP
  - name: http
    port: 42000
    targetPort: http
    protocol: TCP
  - name: xds
    port: 52033
    targetPort: xds
    protocol: TCP
  - name: webhook
    port: 59231
    targetPort: webhook
    protocol: TCP
  selector:
    {{- include "ucloud.provider.selectorLabels" . | nindent 4 }}
