apiVersion: v2
name: ucloud-core
type: application
version: 1.0.2

description: "UCloud is an interactive digital research environment"
appVersion: "2026.1.41"
home: "https://github.com/SDU-eScience/UCloud"
