apiVersion: v2
name: ucloud-core
type: application
version: 1.0.1

description: "UCloud is an interactive digital research environment"
appVersion: "2025.4.171"
home: "https://github.com/SDU-eScience/UCloud"
