nameOverride: ""
fullnameOverride: ""

# networkpolicies?

storage:
  size: 1Gi
  selector: {}
  dataSource: {}
  storageClass: ""
  accessModes:
  - ReadWriteMany
  existingClaim: ""
  subPath: ""

ingress:
  enabled: false
  annotations: {}
  className: ""
  host: ""
  tls: []

global:
  revisionHistoryLimit: 2
  nodeSelector: {}
  annotations: {}
  tolerations: []
  affinity: {}
  service:
    annotations: {}
    type: ClusterIP

accounting:
  image:
    repository: dreg.cloud.sdu.dk/ucloud/core2
    pullPolicy: IfNotPresent
    tag: "2026.1.39"

foundation:
  image:
    repository: dreg.cloud.sdu.dk/ucloud/core2
    pullPolicy: IfNotPresent
    tag: "2026.1.39"

orchestrator:
  image:
    repository: dreg.cloud.sdu.dk/ucloud/core2
    pullPolicy: IfNotPresent
    tag: "2026.1.39"

frontend:
  image:
    repository: dreg.cloud.sdu.dk/ucloud/webclient
    pullPolicy: IfNotPresent
    tag: "2026.1.41"
